### ISSUE TITLE
Implementing cosine similarity

### ISSUE THREAD

**Issue by vilkkomantyla** [vilkkomantyla/Palsternakka#15]
The code is now scoring the documents by summing together the tf-idf values of all the terms in the search query. Next step is to score the documents by comparing the query vector to them.

**Comment by shilosuo** [comment]
Created a new printContentsRanked() function for ranking approach. Queries with AND, OR, NOT will still use matching approach in old printContents() function.

**Comment by vilkkomantyla** [comment]
Nice job! You can delete the issue when you have completed it
