### ISSUE TITLE
Unknown terms

### ISSUE THREAD

**Issue by vilkkomantyla** [vilkkomantyla/Palsternakka#6]
3. If you just copy the code from the tutorial, your program will crash if you enter a word (term) that does not occur in any document in the collection. Modify your program to work correctly also in the case that a term is unknown. For instance, what documents should be retrieved for a search such as: (1) "unknownweirdword", (2) "NOT unknownweirdword", or (3) "unknownweirdword OR this"?  (If this is too difficult, don't get stuck here, but come back to it later.)

**Comment by shilosuo** [comment]
Latasin kauheesti kommentteja sinne, saa siistiä jos tykkää. En tiiä kuinka hyvin niistä saa selvää. Hakulausekkeet, joissa useampi eri operaattori ei toimi, esim. "word1 OR (word2 AND word3)"
